version: "3"
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: production      #to pass it to the arg node_env in dockerfile
    environment:
      - NODE_ENV=production   # to determine which enviroment these configs will run
    command: ["node", "index.js"]      #ovveride cmd in dockerfile        
