version: "3"
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development    #to pass it to the arg node_env in dockerfile        
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASS=xxx
    
      
    command: ["npm", "run", "dev"]   #ovveride cmd in dockerfile
                                     # install dev dependencies 
 